"""
Django settings for scanair project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'eu$@5ttwn(e4a_3ks)#!=s3$&b*%8!9_2im0!zq5kig5gyfltk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'rest_framework',

    'core',
    'currency_layer_api',
    'telegram_bot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'scanair.urls'

WSGI_APPLICATION = 'scanair.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('PG_DB_NAME', 'scanair'),
        'USER': os.environ.get('PG_DB_USER', 'scanair'),
        'PASSWORD': os.environ.get('PG_DB_PASS', 'scanair'),
        'HOST': os.environ.get('PG_DB_HOST', 'localhost'),
        'PORT': os.environ.get('PG_DB_PORT', 5432)
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ]
}

## Currency Layer Info
CURRENCY_LAYER_API = 'http://www.apilayer.net/api'
CURRENCY_LAYER_KEY = os.environ.get('CURRENCYLAYER_API_KEY', None)
